package com.lh.entity;

public class MsArtLable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_art_lable.id
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_art_lable.artId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long artid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_art_lable.lableId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long lableid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_art_lable.id
     *
     * @return the value of ms_art_lable.id
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_art_lable.id
     *
     * @param id the value for ms_art_lable.id
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_art_lable.artId
     *
     * @return the value of ms_art_lable.artId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getArtid() {
        return artid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_art_lable.artId
     *
     * @param artid the value for ms_art_lable.artId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setArtid(Long artid) {
        this.artid = artid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_art_lable.lableId
     *
     * @return the value of ms_art_lable.lableId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getLableid() {
        return lableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_art_lable.lableId
     *
     * @param lableid the value for ms_art_lable.lableId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setLableid(Long lableid) {
        this.lableid = lableid;
    }
}