package com.lh.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsEvaluationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public MsEvaluationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEvaluationidIsNull() {
            addCriterion("evaluationId is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationidIsNotNull() {
            addCriterion("evaluationId is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationidEqualTo(Long value) {
            addCriterion("evaluationId =", value, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidNotEqualTo(Long value) {
            addCriterion("evaluationId <>", value, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidGreaterThan(Long value) {
            addCriterion("evaluationId >", value, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidGreaterThanOrEqualTo(Long value) {
            addCriterion("evaluationId >=", value, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidLessThan(Long value) {
            addCriterion("evaluationId <", value, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidLessThanOrEqualTo(Long value) {
            addCriterion("evaluationId <=", value, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidIn(List<Long> values) {
            addCriterion("evaluationId in", values, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidNotIn(List<Long> values) {
            addCriterion("evaluationId not in", values, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidBetween(Long value1, Long value2) {
            addCriterion("evaluationId between", value1, value2, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andEvaluationidNotBetween(Long value1, Long value2) {
            addCriterion("evaluationId not between", value1, value2, "evaluationid");
            return (Criteria) this;
        }

        public Criteria andObservationIsNull() {
            addCriterion("observation is null");
            return (Criteria) this;
        }

        public Criteria andObservationIsNotNull() {
            addCriterion("observation is not null");
            return (Criteria) this;
        }

        public Criteria andObservationEqualTo(Integer value) {
            addCriterion("observation =", value, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationNotEqualTo(Integer value) {
            addCriterion("observation <>", value, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationGreaterThan(Integer value) {
            addCriterion("observation >", value, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationGreaterThanOrEqualTo(Integer value) {
            addCriterion("observation >=", value, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationLessThan(Integer value) {
            addCriterion("observation <", value, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationLessThanOrEqualTo(Integer value) {
            addCriterion("observation <=", value, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationIn(List<Integer> values) {
            addCriterion("observation in", values, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationNotIn(List<Integer> values) {
            addCriterion("observation not in", values, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationBetween(Integer value1, Integer value2) {
            addCriterion("observation between", value1, value2, "observation");
            return (Criteria) this;
        }

        public Criteria andObservationNotBetween(Integer value1, Integer value2) {
            addCriterion("observation not between", value1, value2, "observation");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesIsNull() {
            addCriterion("sensibilities is null");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesIsNotNull() {
            addCriterion("sensibilities is not null");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesEqualTo(Integer value) {
            addCriterion("sensibilities =", value, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesNotEqualTo(Integer value) {
            addCriterion("sensibilities <>", value, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesGreaterThan(Integer value) {
            addCriterion("sensibilities >", value, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesGreaterThanOrEqualTo(Integer value) {
            addCriterion("sensibilities >=", value, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesLessThan(Integer value) {
            addCriterion("sensibilities <", value, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesLessThanOrEqualTo(Integer value) {
            addCriterion("sensibilities <=", value, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesIn(List<Integer> values) {
            addCriterion("sensibilities in", values, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesNotIn(List<Integer> values) {
            addCriterion("sensibilities not in", values, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesBetween(Integer value1, Integer value2) {
            addCriterion("sensibilities between", value1, value2, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andSensibilitiesNotBetween(Integer value1, Integer value2) {
            addCriterion("sensibilities not between", value1, value2, "sensibilities");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNull() {
            addCriterion("roomId is null");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNotNull() {
            addCriterion("roomId is not null");
            return (Criteria) this;
        }

        public Criteria andRoomidEqualTo(Long value) {
            addCriterion("roomId =", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotEqualTo(Long value) {
            addCriterion("roomId <>", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThan(Long value) {
            addCriterion("roomId >", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThanOrEqualTo(Long value) {
            addCriterion("roomId >=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThan(Long value) {
            addCriterion("roomId <", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThanOrEqualTo(Long value) {
            addCriterion("roomId <=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidIn(List<Long> values) {
            addCriterion("roomId in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotIn(List<Long> values) {
            addCriterion("roomId not in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidBetween(Long value1, Long value2) {
            addCriterion("roomId between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotBetween(Long value1, Long value2) {
            addCriterion("roomId not between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_evaluation
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 22 18:03:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}