package com.lh.entity;

import java.util.Date;

public class MsEvaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.evaluationId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private Long evaluationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.observation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private Integer observation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.sensibilities
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private Integer sensibilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.picture
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.description
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.roomId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.userId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_evaluation.createTime
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.evaluationId
     *
     * @return the value of ms_evaluation.evaluationId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Long getEvaluationid() {
        return evaluationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.evaluationId
     *
     * @param evaluationid the value for ms_evaluation.evaluationId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setEvaluationid(Long evaluationid) {
        this.evaluationid = evaluationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.observation
     *
     * @return the value of ms_evaluation.observation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Integer getObservation() {
        return observation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.observation
     *
     * @param observation the value for ms_evaluation.observation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setObservation(Integer observation) {
        this.observation = observation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.sensibilities
     *
     * @return the value of ms_evaluation.sensibilities
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Integer getSensibilities() {
        return sensibilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.sensibilities
     *
     * @param sensibilities the value for ms_evaluation.sensibilities
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setSensibilities(Integer sensibilities) {
        this.sensibilities = sensibilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.picture
     *
     * @return the value of ms_evaluation.picture
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.picture
     *
     * @param picture the value for ms_evaluation.picture
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.description
     *
     * @return the value of ms_evaluation.description
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.description
     *
     * @param description the value for ms_evaluation.description
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.roomId
     *
     * @return the value of ms_evaluation.roomId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.roomId
     *
     * @param roomid the value for ms_evaluation.roomId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.userId
     *
     * @return the value of ms_evaluation.userId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.userId
     *
     * @param userid the value for ms_evaluation.userId
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_evaluation.createTime
     *
     * @return the value of ms_evaluation.createTime
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_evaluation.createTime
     *
     * @param createtime the value for ms_evaluation.createTime
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}