package com.lh.entity;

public class MsLable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_lable.lableId
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long lableid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_lable.description
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_lable.lableId
     *
     * @return the value of ms_lable.lableId
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getLableid() {
        return lableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_lable.lableId
     *
     * @param lableid the value for ms_lable.lableId
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setLableid(Long lableid) {
        this.lableid = lableid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_lable.description
     *
     * @return the value of ms_lable.description
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_lable.description
     *
     * @param description the value for ms_lable.description
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}