package com.lh.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MsOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.orderId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.id
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.startDate
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.outDate
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Date outdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.number
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.roomId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.landId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Long landid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.money
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.deposit
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private BigDecimal deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.status
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.checkPerson
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private String checkperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.cardNo
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.phone
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.userId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.createTime
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    private Date createtime;



    private String ordernum;
    private String result;
    private Date resultdate;
    private String tradenum;
    private String orderinfo;

    public String getOrderinfo() {
        return orderinfo;
    }

    public void setOrderinfo(String orderinfo) {
        this.orderinfo = orderinfo;
    }

    public String getTradenum() {
        return tradenum;
    }

    public void setTradenum(String tradenum) {
        this.tradenum = tradenum;
    }

    public String getOrdernum() {
        return ordernum;
    }

    public void setOrdernum(String ordernum) {
        this.ordernum = ordernum;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public Date getResultdate() {
        return resultdate;
    }

    public void setResultdate(Date resultdate) {
        this.resultdate = resultdate;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.orderId
     *
     * @return the value of ms_order.orderId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.orderId
     *
     * @param orderid the value for ms_order.orderId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.id
     *
     * @return the value of ms_order.id
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.id
     *
     * @param id the value for ms_order.id
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.startDate
     *
     * @return the value of ms_order.startDate
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.startDate
     *
     * @param startdate the value for ms_order.startDate
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.outDate
     *
     * @return the value of ms_order.outDate
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Date getOutdate() {
        return outdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.outDate
     *
     * @param outdate the value for ms_order.outDate
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setOutdate(Date outdate) {
        this.outdate = outdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.number
     *
     * @return the value of ms_order.number
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.number
     *
     * @param number the value for ms_order.number
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.roomId
     *
     * @return the value of ms_order.roomId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.roomId
     *
     * @param roomid the value for ms_order.roomId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.landId
     *
     * @return the value of ms_order.landId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Long getLandid() {
        return landid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.landId
     *
     * @param landid the value for ms_order.landId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setLandid(Long landid) {
        this.landid = landid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.money
     *
     * @return the value of ms_order.money
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.money
     *
     * @param money the value for ms_order.money
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.deposit
     *
     * @return the value of ms_order.deposit
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.deposit
     *
     * @param deposit the value for ms_order.deposit
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.status
     *
     * @return the value of ms_order.status
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.status
     *
     * @param status the value for ms_order.status
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.checkPerson
     *
     * @return the value of ms_order.checkPerson
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public String getCheckperson() {
        return checkperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.checkPerson
     *
     * @param checkperson the value for ms_order.checkPerson
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setCheckperson(String checkperson) {
        this.checkperson = checkperson == null ? null : checkperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.cardNo
     *
     * @return the value of ms_order.cardNo
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.cardNo
     *
     * @param cardno the value for ms_order.cardNo
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.phone
     *
     * @return the value of ms_order.phone
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.phone
     *
     * @param phone the value for ms_order.phone
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.userId
     *
     * @return the value of ms_order.userId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.userId
     *
     * @param userid the value for ms_order.userId
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.createTime
     *
     * @return the value of ms_order.createTime
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.createTime
     *
     * @param createtime the value for ms_order.createTime
     *
     * @mbggenerated Mon Apr 15 08:29:49 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}