package com.lh.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MsOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.orderId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
<<<<<<< HEAD
     * This field corresponds to the database column ms_order.startDate
     *
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * This field corresponds to the database column ms_order.orderNumber
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    private String ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.result
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.resultDate
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    private Date resultdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.tradenum
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    private String tradenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.derinfo
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    private String derinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.startDate
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.outDate
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Date outdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.number
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.roomId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.landId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long landid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.money
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.deposit
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private BigDecimal deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.status
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.checkPerson
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private String checkperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.cardNo
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.phone
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.userId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_order.createTime
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Date createtime;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.orderId
     *
     * @return the value of ms_order.orderId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.orderId
     *
     * @param orderid the value for ms_order.orderId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
<<<<<<< HEAD
=======
     * This method returns the value of the database column ms_order.orderNumber
     *
     * @return the value of ms_order.orderNumber
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.orderNumber
     *
     * @param ordernumber the value for ms_order.orderNumber
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.result
     *
     * @return the value of ms_order.result
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.result
     *
     * @param result the value for ms_order.result
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.resultDate
     *
     * @return the value of ms_order.resultDate
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public Date getResultdate() {
        return resultdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.resultDate
     *
     * @param resultdate the value for ms_order.resultDate
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public void setResultdate(Date resultdate) {
        this.resultdate = resultdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.tradenum
     *
     * @return the value of ms_order.tradenum
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public String getTradenum() {
        return tradenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.tradenum
     *
     * @param tradenum the value for ms_order.tradenum
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public void setTradenum(String tradenum) {
        this.tradenum = tradenum == null ? null : tradenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.derinfo
     *
     * @return the value of ms_order.derinfo
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public String getDerinfo() {
        return derinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.derinfo
     *
     * @param derinfo the value for ms_order.derinfo
     *
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
     */
    public void setDerinfo(String derinfo) {
        this.derinfo = derinfo == null ? null : derinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     * This method returns the value of the database column ms_order.startDate
     *
     * @return the value of ms_order.startDate
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.startDate
     *
     * @param startdate the value for ms_order.startDate
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.outDate
     *
     * @return the value of ms_order.outDate
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Date getOutdate() {
        return outdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.outDate
     *
     * @param outdate the value for ms_order.outDate
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setOutdate(Date outdate) {
        this.outdate = outdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.number
     *
     * @return the value of ms_order.number
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.number
     *
     * @param number the value for ms_order.number
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.roomId
     *
     * @return the value of ms_order.roomId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.roomId
     *
     * @param roomid the value for ms_order.roomId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.landId
     *
     * @return the value of ms_order.landId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getLandid() {
        return landid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.landId
     *
     * @param landid the value for ms_order.landId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setLandid(Long landid) {
        this.landid = landid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.money
     *
     * @return the value of ms_order.money
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.money
     *
     * @param money the value for ms_order.money
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.deposit
     *
     * @return the value of ms_order.deposit
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.deposit
     *
     * @param deposit the value for ms_order.deposit
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.status
     *
     * @return the value of ms_order.status
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.status
     *
     * @param status the value for ms_order.status
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.checkPerson
     *
     * @return the value of ms_order.checkPerson
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public String getCheckperson() {
        return checkperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.checkPerson
     *
     * @param checkperson the value for ms_order.checkPerson
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setCheckperson(String checkperson) {
        this.checkperson = checkperson == null ? null : checkperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.cardNo
     *
     * @return the value of ms_order.cardNo
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.cardNo
     *
     * @param cardno the value for ms_order.cardNo
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.phone
     *
     * @return the value of ms_order.phone
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.phone
     *
     * @param phone the value for ms_order.phone
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.userId
     *
     * @return the value of ms_order.userId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.userId
     *
     * @param userid the value for ms_order.userId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_order.createTime
     *
     * @return the value of ms_order.createTime
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_order.createTime
     *
     * @param createtime the value for ms_order.createTime
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}