package com.lh.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MsRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.roomId
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.roomName
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.rooming
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String rooming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.type
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.rentWay
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private Integer rentway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.area
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.doormodel
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String doormodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.companion
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String companion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.bedType
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String bedtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.bedSize
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String bedsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.facility
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String facility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.address
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.areasNear
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private String areasnear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.roomNum
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private Integer roomnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.price
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.status
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.landlordId
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private Long landlordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.createTime
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.roomId
     *
     * @return the value of ms_room.roomId
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.roomId
     *
     * @param roomid the value for ms_room.roomId
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.roomName
     *
     * @return the value of ms_room.roomName
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.roomName
     *
     * @param roomname the value for ms_room.roomName
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.rooming
     *
     * @return the value of ms_room.rooming
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getRooming() {
        return rooming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.rooming
     *
     * @param rooming the value for ms_room.rooming
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setRooming(String rooming) {
        this.rooming = rooming == null ? null : rooming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.type
     *
     * @return the value of ms_room.type
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.type
     *
     * @param type the value for ms_room.type
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.rentWay
     *
     * @return the value of ms_room.rentWay
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public Integer getRentway() {
        return rentway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.rentWay
     *
     * @param rentway the value for ms_room.rentWay
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setRentway(Integer rentway) {
        this.rentway = rentway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.area
     *
     * @return the value of ms_room.area
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.area
     *
     * @param area the value for ms_room.area
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.doormodel
     *
     * @return the value of ms_room.doormodel
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getDoormodel() {
        return doormodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.doormodel
     *
     * @param doormodel the value for ms_room.doormodel
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setDoormodel(String doormodel) {
        this.doormodel = doormodel == null ? null : doormodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.companion
     *
     * @return the value of ms_room.companion
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getCompanion() {
        return companion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.companion
     *
     * @param companion the value for ms_room.companion
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setCompanion(String companion) {
        this.companion = companion == null ? null : companion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.bedType
     *
     * @return the value of ms_room.bedType
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getBedtype() {
        return bedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.bedType
     *
     * @param bedtype the value for ms_room.bedType
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setBedtype(String bedtype) {
        this.bedtype = bedtype == null ? null : bedtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.bedSize
     *
     * @return the value of ms_room.bedSize
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getBedsize() {
        return bedsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.bedSize
     *
     * @param bedsize the value for ms_room.bedSize
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setBedsize(String bedsize) {
        this.bedsize = bedsize == null ? null : bedsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.facility
     *
     * @return the value of ms_room.facility
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getFacility() {
        return facility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.facility
     *
     * @param facility the value for ms_room.facility
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setFacility(String facility) {
        this.facility = facility == null ? null : facility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.address
     *
     * @return the value of ms_room.address
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.address
     *
     * @param address the value for ms_room.address
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.areasNear
     *
     * @return the value of ms_room.areasNear
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public String getAreasnear() {
        return areasnear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.areasNear
     *
     * @param areasnear the value for ms_room.areasNear
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setAreasnear(String areasnear) {
        this.areasnear = areasnear == null ? null : areasnear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.roomNum
     *
     * @return the value of ms_room.roomNum
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public Integer getRoomnum() {
        return roomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.roomNum
     *
     * @param roomnum the value for ms_room.roomNum
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setRoomnum(Integer roomnum) {
        this.roomnum = roomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.price
     *
     * @return the value of ms_room.price
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.price
     *
     * @param price the value for ms_room.price
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.status
     *
     * @return the value of ms_room.status
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.status
     *
     * @param status the value for ms_room.status
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.landlordId
     *
     * @return the value of ms_room.landlordId
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public Long getLandlordid() {
        return landlordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.landlordId
     *
     * @param landlordid the value for ms_room.landlordId
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setLandlordid(Long landlordid) {
        this.landlordid = landlordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.createTime
     *
     * @return the value of ms_room.createTime
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.createTime
     *
     * @param createtime the value for ms_room.createTime
     *
     * @mbggenerated Thu Apr 11 10:41:04 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}