package com.lh.entity;

public class MsUserArt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_art.id
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_art.userId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_art.artId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    private Long artid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_art.id
     *
     * @return the value of ms_user_art.id
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_art.id
     *
     * @param id the value for ms_user_art.id
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_art.userId
     *
     * @return the value of ms_user_art.userId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_art.userId
     *
     * @param userid the value for ms_user_art.userId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_art.artId
     *
     * @return the value of ms_user_art.artId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public Long getArtid() {
        return artid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_art.artId
     *
     * @param artid the value for ms_user_art.artId
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    public void setArtid(Long artid) {
        this.artid = artid;
    }
}