package com.lh.mapper;

import com.lh.entity.MsArticle;
import com.lh.entity.MsArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long artid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsArticle> selectByExample(MsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsArticle selectByPrimaryKey(Long artid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsArticle record, @Param("example") MsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsArticle record, @Param("example") MsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsArticle record);
}