package com.lh.mapper;

import com.lh.entity.MsDesc;
import com.lh.entity.MsDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long descid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsDesc> selectByExample(MsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsDesc selectByPrimaryKey(Long descid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsDesc record, @Param("example") MsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsDesc record, @Param("example") MsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_desc
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsDesc record);
}