package com.lh.mapper;

import com.lh.entity.MsEvaluation;
import com.lh.entity.MsEvaluationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int countByExample(MsEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int deleteByExample(MsEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int deleteByPrimaryKey(Long evaluationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int insert(MsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int insertSelective(MsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    List<MsEvaluation> selectByExample(MsEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    MsEvaluation selectByPrimaryKey(Long evaluationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") MsEvaluation record, @Param("example") MsEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int updateByExample(@Param("record") MsEvaluation record, @Param("example") MsEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int updateByPrimaryKeySelective(MsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_evaluation
     *
     * @mbggenerated Mon Apr 22 18:03:21 CST 2019
     */
    int updateByPrimaryKey(MsEvaluation record);
}