package com.lh.mapper;

import com.lh.entity.MsLable;
import com.lh.entity.MsLableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsLableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsLableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsLableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long lableid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsLable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsLable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsLable> selectByExample(MsLableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsLable selectByPrimaryKey(Long lableid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsLable record, @Param("example") MsLableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsLable record, @Param("example") MsLableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsLable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_lable
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsLable record);
}