package com.lh.mapper;

import com.lh.entity.MsNotice;
import com.lh.entity.MsNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsNotice> selectByExample(MsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsNotice selectByPrimaryKey(Long noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsNotice record, @Param("example") MsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsNotice record, @Param("example") MsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_notice
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsNotice record);
}