package com.lh.mapper;

import com.lh.entity.MsOrder;
import com.lh.entity.MsOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsOrder> selectByExample(MsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsOrder selectByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsOrder record, @Param("example") MsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsOrder record, @Param("example") MsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_order
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsOrder record);
}