package com.lh.mapper;

import com.lh.entity.MsReview;
import com.lh.entity.MsReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long reviewid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsReview> selectByExample(MsReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsReview selectByPrimaryKey(Long reviewid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsReview record, @Param("example") MsReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsReview record, @Param("example") MsReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_review
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsReview record);
}