package com.lh.mapper;

import com.lh.entity.MsReport;
import com.lh.entity.MsReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long repordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsReport> selectByExample(MsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsReport selectByPrimaryKey(Long repordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsReport record, @Param("example") MsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsReport record, @Param("example") MsReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_report
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsReport record);
}