package com.lh.mapper;

import com.lh.entity.MsRoom;
import com.lh.entity.MsRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int countByExample(MsRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int deleteByExample(MsRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int deleteByPrimaryKey(Long roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int insert(MsRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int insertSelective(MsRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    List<MsRoom> selectByExample(MsRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    MsRoom selectByPrimaryKey(Long roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") MsRoom record, @Param("example") MsRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int updateByExample(@Param("record") MsRoom record, @Param("example") MsRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int updateByPrimaryKeySelective(MsRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
     */
    int updateByPrimaryKey(MsRoom record);
}