package com.lh.mapper;

import com.lh.entity.MsSleeper;
import com.lh.entity.MsSleeperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsSleeperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsSleeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsSleeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long sleeperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsSleeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsSleeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsSleeper> selectByExample(MsSleeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsSleeper selectByPrimaryKey(Long sleeperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsSleeper record, @Param("example") MsSleeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsSleeper record, @Param("example") MsSleeperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsSleeper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sleeper
     *
<<<<<<< HEAD
     * @mbggenerated Fri Apr 19 22:14:25 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsSleeper record);
}