package com.lh.mapper;

import com.lh.entity.MsUserHobby;
import com.lh.entity.MsUserHobbyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsUserHobbyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int countByExample(MsUserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByExample(MsUserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insert(MsUserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int insertSelective(MsUserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    List<MsUserHobby> selectByExample(MsUserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    MsUserHobby selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExampleSelective(@Param("record") MsUserHobby record, @Param("example") MsUserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByExample(@Param("record") MsUserHobby record, @Param("example") MsUserHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKeySelective(MsUserHobby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user_hobby
     *
<<<<<<< HEAD
     * @mbggenerated Mon Apr 15 08:21:22 CST 2019
=======
     * @mbggenerated Fri Apr 19 08:42:06 CST 2019
>>>>>>> 6e13e5717372feaa6e93f20c55561ca38f98c880
     */
    int updateByPrimaryKey(MsUserHobby record);
}